#!/bin/bash

set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-/mnt/hwfile/linzhanhui/projects/starVLA}"
WATCH_SCRIPT="${WATCH_SCRIPT:-${PROJECT_DIR}/examples/LIBERO/train_files/watch_libero_clean_checked_generic_8g.sh}"

# Friendly user-facing knobs. Both upper-case and legacy lower-case spellings are accepted.
FRAMEWORK_NAME="${FRAMEWORK_NAME:-${Framework_name:-QwenOFT}}"
BASE_VLM="${BASE_VLM:-${base_vlm:-/mnt/petrelfs/linzhanhui/.cache/huggingface/hub/models--Qwen--Qwen3-VL-4B-Instruct/snapshots/ebb281ec70b05090aa6165b016eac8ec08e71b17}}"
CONFIG_YAML="${CONFIG_YAML:-${config_yaml:-examples/LIBERO/train_files/starvla_cotrain_libero.yaml}}"
LIBERO_DATA_ROOT="${LIBERO_DATA_ROOT:-${libero_data_root:-${PROJECT_DIR}/playground/Datasets/LEROBOT_LIBERO_DATA}}"
DATA_MIX="${DATA_MIX:-${data_mix:-libero_goal}}"
RUN_ROOT_DIR="${RUN_ROOT_DIR:-${run_root_dir:-/mnt/petrelfs/linzhanhui/runs_inspect/starVLA}}"
RUN_ID="${RUN_ID:-${run_id:-}}"

NNODES="${NNODES:-1}"
GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
CPUS_PER_TASK="${CPUS_PER_TASK:-128}"
PER_DEVICE_BS="${PER_DEVICE_BS:-4}"
GRAD_ACCUM="${GRAD_ACCUM:-2}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-}"
NUM_WARMUP_STEPS="${NUM_WARMUP_STEPS:-}"
ACTION_GOAL_LANG_PROB="${ACTION_GOAL_LANG_PROB:-}"
SAVE_INTERVAL="${SAVE_INTERVAL:-}"
LOGGING_FREQUENCY="${LOGGING_FREQUENCY:-}"
EVAL_INTERVAL="${EVAL_INTERVAL:-}"

WANDB_PROJECT="${WANDB_PROJECT:-starVLA_LIBERO}"
WANDB_ENTITY="${WANDB_ENTITY:-radiance}"
ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION:-flash_attention_2}"
PARTITION="${PARTITION:-eailab_link}"
ACCOUNT="${ACCOUNT:-research}"
TIME_LIMIT="${TIME_LIMIT:-5-00:00:00}"
DISABLE_WANDB_PROXY="${DISABLE_WANDB_PROXY:-0}"
WANDB_HTTP_PROXY="${WANDB_HTTP_PROXY:-}"
WANDB_HTTPS_PROXY="${WANDB_HTTPS_PROXY:-}"

if [[ ! -x "${WATCH_SCRIPT}" ]]; then
  echo "[ERROR] watch script not found or not executable: ${WATCH_SCRIPT}" >&2
  exit 1
fi

cd "${PROJECT_DIR}"

exec env \
  PROJECT_DIR="${PROJECT_DIR}" \
  FRAMEWORK_NAME="${FRAMEWORK_NAME}" \
  BASE_VLM="${BASE_VLM}" \
  CONFIG_YAML="${CONFIG_YAML}" \
  LIBERO_DATA_ROOT="${LIBERO_DATA_ROOT}" \
  DATA_MIX="${DATA_MIX}" \
  RUN_ROOT_DIR="${RUN_ROOT_DIR}" \
  RUN_ID="${RUN_ID}" \
  NNODES="${NNODES}" \
  GPUS_PER_NODE="${GPUS_PER_NODE}" \
  CPUS_PER_TASK="${CPUS_PER_TASK}" \
  PER_DEVICE_BS="${PER_DEVICE_BS}" \
  GRAD_ACCUM="${GRAD_ACCUM}" \
  MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS}" \
  NUM_WARMUP_STEPS="${NUM_WARMUP_STEPS}" \
  ACTION_GOAL_LANG_PROB="${ACTION_GOAL_LANG_PROB}" \
  SAVE_INTERVAL="${SAVE_INTERVAL}" \
  LOGGING_FREQUENCY="${LOGGING_FREQUENCY}" \
  EVAL_INTERVAL="${EVAL_INTERVAL}" \
  WANDB_PROJECT="${WANDB_PROJECT}" \
  WANDB_ENTITY="${WANDB_ENTITY}" \
  ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION}" \
  PARTITION="${PARTITION}" \
  ACCOUNT="${ACCOUNT}" \
  TIME_LIMIT="${TIME_LIMIT}" \
  DISABLE_WANDB_PROXY="${DISABLE_WANDB_PROXY}" \
  WANDB_HTTP_PROXY="${WANDB_HTTP_PROXY}" \
  WANDB_HTTPS_PROXY="${WANDB_HTTPS_PROXY}" \
  bash "${WATCH_SCRIPT}"
